# Ansible script that will configure server
---
- hosts: "{{ hosts }}"
  become: true
  tasks:
    - name: Stop php-fpm service
      service:
        name: php{{php_version}}-fpm
        state: stopped
    - name: Disable php-fpm service
      systemd:
        name: php{{php_version}}-fpm
        enabled: no
    - name: Change image permissions
      file:
        path: "/home/{{username}}/test_files/static/bulbasaur.png"
        owner: "{{username}}"
        group: "{{username}}"
        mode: "0400"
    - name: Copy broken nginx configuration
      template:
        src: "roles/files_and_config_setup/templates/broken.nginx.http.conf.j2"
        dest: "/etc/nginx/sites-available/{{subdomain}}"
    - name: Force reload nginx configuration
      service: 
        name: nginx
        state: reloaded